# Python Tutorial
(mostly compliments of Tiago Ferreira, Van Meyel Lab - McGill University)

## We can write comments in markdown

### With different header sizes

### Here is how we write a comment

In [1]:
"""
Triple quotes are used for large multi-line comments, and
typically to document functions and modules (Docstrings)
"""

'\nTriple quotes are used for large multi-line comments, and\ntypically to document functions and modules (Docstrings)\n'

### Here is how we print

In [2]:
print ("Hello Python!")
print

Hello Python!


<function print>

### here is some math:

In [5]:
a = 1+1 # Sum
b = 2*4 # Multiplication
c = 2**4 # Exponentiation (2^14 = 16)
print ("Print variables a, b, c", a, b, c)
print

Print variables a, b, c 2 8 16


<function print>

### By the way you can multiply strings... try...

In [9]:
print ("Multiply hello by 3: ", 3*"hello ")

Multiply hello by 3:  hello hello hello 


### Logical Operators

In [10]:
print ("(a is b):", (a is b))
print ("a==2:", a==2)
print ("a is not b and b!=2:", a is not b and b!=2)
print

(a is b): False
a==2: True
a is not b and b!=2: True


<function print>

Lists are indexed sequences of items. The 1st index (item position) is zero, the 2nd index is one, etc.  A list can contain any type of item.

In [11]:
my_list =[]# An empty list
my_list = [1,2,3,4,5,6]# A prefilled list
my_list[0] = "string"# Assign new value to an initialized index
my_list.append(7)# Append new item to list
print ("Here is the list:", my_list)
my_list.pop()# Remove last element from list
print ("And here it is after calling list.pop():", my_list)
print

Here is the list: ['string', 2, 3, 4, 5, 6, 7]
And here it is after calling list.pop(): ['string', 2, 3, 4, 5, 6]


<function print>

At any time we can get help on a type.  Try typing help(list)

In [12]:
help(list)

Help on class list in module builtins:

class list(object)
 |  list(iterable=(), /)
 |  
 |  Built-in mutable sequence.
 |  
 |  If no argument is given, the constructor creates a new empty list.
 |  The argument must be an iterable if specified.
 |  
 |  Methods defined here:
 |  
 |  __add__(self, value, /)
 |      Return self+value.
 |  
 |  __contains__(self, key, /)
 |      Return key in self.
 |  
 |  __delitem__(self, key, /)
 |      Delete self[key].
 |  
 |  __eq__(self, value, /)
 |      Return self==value.
 |  
 |  __ge__(self, value, /)
 |      Return self>=value.
 |  
 |  __getattribute__(self, name, /)
 |      Return getattr(self, name).
 |  
 |  __getitem__(...)
 |      x.__getitem__(y) <==> x[y]
 |  
 |  __gt__(self, value, /)
 |      Return self>value.
 |  
 |  __iadd__(self, value, /)
 |      Implement self+=value.
 |  
 |  __imul__(self, value, /)
 |      Implement self*=value.
 |  
 |  __init__(self, /, *args, **kwargs)
 |      Initialize self.  See help(type(self))

Working with dictionaries: Dictionaries store mappings between <keys> and <values>. Keys can be unique strings or numbers (or any immutable type). Values can be anything: a string, a number, an expression, or any other object.

In [13]:
my_dict = {}# An empty dictionary
my_dict = {"John":1234, "my_list":my_list}# A prefilled dictionary
my_dict['Best Team']="Blue Jays"# Add a key:value pair

# Create a list from a generator expression (the <value>) and
# associate it to a variable (the <key>)
a = "Bit-depths"
my_dict[a] = [2**x for x in (1, 8, 16, 32)]

# Looking up values:
print ("my_dict[\"Best Team\"]", my_dict["Best Team"])
print ("my_dict[\"my_list\"]", my_dict["my_list"])
print ("my_dict[a]", my_dict[a])

my_dict["Best Team"] Blue Jays
my_dict["my_list"] ['string', 2, 3, 4, 5, 6]
my_dict[a] [2, 256, 65536, 4294967296]


Try a key that doesn't exist

In [14]:
try:
    my_var = my_dict["Expos"]
except KeyError:
    print ("Expos is not in the dictionary")
    print ("They moved to Washington in 2005 :(")
print

Expos is not in the dictionary
They moved to Washington in 2005 :(


<function print>

### Control Flow
(If, and for statements)

If statement (Indentation is critical!)

In [15]:
a,b = 10,20
my_list = [1, 2, 3, 4]

# An if statement: Indentation is critical in python!
if a in my_list:
	print (a, "is in the list")
elif b in my_list:
	print (b, "is in the list")
else:
    print ("Neither", a, "or", b, "are in in the list")

Neither 10 or 20 are in in the list


Modify to detect if both are in the list

In [16]:
a,b=1,3

list = [1, 2, 3, 4]

# An if statement: Indentation is critical in python!
if a in my_list and b not in my_list:
	print (a, "is in the list")
elif b in my_list and a not in my_list:
	print (b, "is in the list")
elif a in my_list and b in my_list:
	print ("a ",a," and b ",b," are both in the list")
else:
	print ("Neither", a, "or", b, "are in in the list")

a  1  and b  3  are both in the list


### For loops
Create a list of numbers (ussually using the range function) and then loop through them

In [17]:
range_list=range(1,10)
print
print ("Here is a list of numbers created with range: ",range_list)

Here is a list of numbers created with range:  range(1, 10)


Now we can use the list to make a loop

In [18]:
print ("Loop using the list we created above: ")
for i in range_list:
    print (i)

Loop using the list we created above: 
1
2
3
4
5
6
7
8
9


We can also loop through lists

In [21]:
print ("Loop through a list")

team_list=["Blue Jays", "Yankees", "Red Sox", "Rays", "Orioles"]

for team in team_list:
    print ("The team is: ", team)

Loop through a list
The team is:  Blue Jays
The team is:  Yankees
The team is:  Red Sox
The team is:  Rays
The team is:  Orioles


## The import statement is used to access additional modules
This is really!!!! important for data analysis, for data analysis we use the numpy, pandas and scikit-learn modules extensively.

In [22]:
# Importing a Python module:
import math
print ("[Line 09]", "Python PI=", math.pi) # https://docs.python.org/2/library/math.html


# The import statement can occur anywhere in a script
my_teams = ["Blue Jays", "Oilers", "Raptors", "Bills"]
import random
print ("A random team:", random.choice(my_teams)) # https://docs.python.org/2/library/random.html

[Line 09] Python PI= 3.141592653589793
A random team: Raptors


Of course we can get help on modules...

In [23]:
help(random.choice)

Help on method choice in module random:

choice(seq) method of random.Random instance
    Choose a random element from a non-empty sequence.



## Functions
We can define functions using 'def'.  As ussual indentation is important. 

In [24]:
def today():
    import datetime
    return datetime.date.today()

In [26]:
print (today())

2019-12-17


We can define functions with arguments

In [27]:
# A Function with arguments:
def minFunction(a, b):
    """This function returns the smallest of two arguments"""
    if a < b:
        return a
    else:
        return b

print (minFunction(10,20), "is smaller")

10 is smaller


## List vs. Array
List is a generic container (can contain anything)

Numpy is a python module used for math

Array is a numpy structure used for numeric calculations

In [33]:
import numpy as np

n=10
a_list = [range(1,n)]
a_array = np.arange(n)

In [34]:
print (type(a_list))
print (type(a_array))

<class 'list'>
<class 'numpy.ndarray'>


Try multiplying both the list and the array

In [35]:
print ("multiply the list")
mul_list=a_list*3
print (mul_list)
print ("multiply the array")
mul_array=a_array*3
print (mul_array)

multiply the list
[range(1, 10), range(1, 10), range(1, 10)]
multiply the array
[ 0  3  6  9 12 15 18 21 24 27]


Let's try adding both the list and the array

In [36]:
add_list=a_list+3
print (add_list)

TypeError: can only concatenate list (not "int") to list

In [38]:
add_array=a_array+3
print (add_array)

[ 3  4  5  6  7  8  9 10 11 12]


Raise to a power

In [39]:
pow_list=a_list**3
print (pow_list)

TypeError: unsupported operand type(s) for ** or pow(): 'list' and 'int'

In [40]:
pow_array=a_array**3	
print (pow_array)

[  0   1   8  27  64 125 216 343 512 729]
